auto: true

markdown: rdiscount
highlighter: pygments
paginate: 5
paginate_path: "project/page:num"
permalink: /:title

title: 疯子伟哥的世界
url: http://www.itweige.com
feed: /atom.xml
author_info: <a href="http://www.itweige.com/">Masterwind</a>
