auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: itweige.com
url: http://www.itweige.com
feed: /atom.xml
author_info: <a href="http://www.itweige.com/">Masterwind</a>
